### ISSUE TITLE
Create loading screen?

### ISSUE THREAD

**Issue by JaakkoLipsanen** [JaakkoLipsanen/evento#28]
Do we want to create a some kind of loading page or something that is displayed before the actual pages? The thing is that our backend is usually asleep and it takes like 5-10 seconds for it to wake up and return data, so it might be a bit confusing if the pages get loaded but you dont see any data :/

**Comment by anttilip** [comment]
Yeah it would be great. By the way if we decide to move front-end to Heroku it sleeps also so the loading time would be 10-20 seconds :/

**Comment by JaakkoLipsanen** [comment]
Yep

**Comment by JaakkoLipsanen** [comment]
This will kinda be implemented in #59
