### ISSUE TITLE
Require signing in to use the website

### ISSUE THREAD

**Issue by anttilip** [JaakkoLipsanen/evento#40]
Requiring signing in would simplify the design a bit. When a user would enter the website they need to sign in or register. When signed in, the user would be redirected to the front page.

**Comment by anttilip** [comment]
One inconvenience is when following a link to the website results in redirect to the sign in page and the link url is 'lost'. This could be solved with a cookie or some global variable etc.

**Comment by JaakkoLipsanen** [comment]
I agree that this is probably a decent idea, especially since I like to think evento as an app instead of website.
