### ISSUE TITLE
Stop using fetch-mock and instead mock the api.js

### ISSUE THREAD

**Issue by JaakkoLipsanen** [JaakkoLipsanen/evento#56]
The result will be much, much clearer test code.

**Comment by anttilip** [comment]
But how would we test components without fetch-mock?

**Comment by JaakkoLipsanen** [comment]
By mocking api.js functions. For example, we mock `api.getEvent(eventId)` instead of `fetch('/events/${eventId}')` etc

**Comment by anttilip** [comment]
Hmm that might be a good idea. That also makes it possible to test e.g. POST request parameters, which I didn't manage to get working with fetch-mock

**Comment by JaakkoLipsanen** [comment]
Implemented in #57
